### PR TITLE
add bind_to feature to support VPN's

### PR DESCRIPTION
**Pull request by blmpl**
This change allows to bind pianobar to vpn interface and use it instead of proxy.
If you don't want to route whole traffic by vpn, that's the simples solution to use it only by pianobar.
Works fine for a while so I thought it's worth to share :)

### CODE REVIEW

**Comment by PromyLOPh** [comment]
Hm, apparently my comment got eaten by the spam filter. Here it is:

Could be useful and the patch is simple enough. But the setting  again
definitely needs documentation in the manpage, mentioning your VPN 
use-case. It should refer to 
https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html as well due to its 
special syntax. And the bind_to variable (not setting) should be 
camelCase. You want to give it a shot?

**Comment by blmpl** [comment]
Sure, please take a look now. I'm not the best (probably even good) documentation writer, so please let me know if you think it should be changed somehow or just use my attempt as example "use case". (It's the first man page I edited so far ;) ) 
To be honest I didn't know about if! and host! prefixes. Code works good without it, but probably it's a bit faster. I'm not sure if it's worth to mention about them as it could be confusing for users.

btw - I suppose that you heard this 100times so far, but I would like to thank you for this program :)

**Comment by PromyLOPh** [comment]
Here’s my turn: 79844540a83d7acaf8166b3081913f1968ebf78c

The OpenVPN config is probably a litte too much, so I replaced it with
the essential bits (i.e. nopull). I’ll push that commit into master,
unless I messed up something.

> btw - I suppose that you heard this 100times so far, but I would like
> to thank you for this program :)
Much appreciated.

**Comment by blmpl** [comment]
looks good to me - thanks :)

**Pull request closed without merging**
