### PR TITLE
Allow optional use of PolarSSL instead of GNUTLS

### PR DESCRIPTION
**Pull request by thess**
Submitting this work upstream from other work I;ve done integrating pianod into OpenWrt package repo. The pianod work has been tested on a number of  Linux platforms  Thanks to  @thedmd (pianobar-windows)

Usage:
>Install libpolarssl-dev (or whatever your platform uses)
>$make POLARSSL=1

### CODE REVIEW

**Comment by PromyLOPh** [comment]
What are the advantages of PolarSSL? Why should we support two TLS
implementations?

**Comment by thess** [comment]
My main motivation was size added to an OpenWrt configuration. Essentially, on embedded systems, like OpenWrt, running on a platform with limited Flash & RAM, PolarSSL seems to be the crypto lib of choice. At least on OpenWrt, it is usually always present and I decided to avoid adding another crypto lib just to play music. Keeping it simple - It is a bit cleaner implementation and has a somewhat saner API than OpenSSL and GNUTLS.

**Comment by PromyLOPh** [comment]
I see. Is libcurl (with TLS) available on OpenWrt?

Wrt the patch:
1) Makefile: Is pkg-config available for PolarSSL?
2) Why the BUFFER_CAST?
3) Is waith->request.sslCtx a pointer to hide the struct’s definition or
   to allocate it on the heap (i.e. too big for stack)?
4) Does PolarSSL support SNI? Your changes do not seem to be using
   waith->url.host anywhere.

**Comment by thess** [comment]
Wrt libcurl -- Yes, one can build it with a choice of SSL libraries and several other options. The default SSL lib is PolarSSL.

1 - No pkg-config that I know of
2 - Avoids compile-time warnings (a personal preference)
3 - request.sslCtx is allocated on the heap and freed inside WaitressFetchCall() (another personal preference)
4- Yes it does. I missed that. I will update my change to use ssl_set_hostname()

**Comment by thess** [comment]
Updated patch for item 4 above

**Comment by PromyLOPh** [comment]
> Wrt libcurl -- Yes, one can build it with a choice of SSL libraries
> and several other options. The default SSL lib is PolarSSL.
libcurl works surprisingly well (see “curl” feature branch) – it’s much
faster than libwaitress too (probably due to TLS session resumption and
by keeping connections alive). I suppose dropping libwaitress and going
with libcurl would make everybody’s life easier.

**Comment by thess** [comment]
Nice touch -- It certainly makes the implementation of pianobar more compact though making it dependent on a number of external libraries with a larger amount of size overhead (libavcodec & friends for example). Go for it!

**Comment by PromyLOPh** [comment]
Alright, commit 4458cbab76fd98989fa2d4260dd20bbbd66297a4 switches back
to curl.

> […] though making it dependent on a number of external libraries with
> a larger amount of size overhead (libavcodec & friends for example).
Well, I don’t see how we could get away without ffmpeg right now. As for
libcurl: Sure, you could argue that using curl adds a lot of bloat
(because curl supports much more than HTTP), but on the other hand not
using it when it’s already installed (I assume that’s true for most
users) adds the additional weight of libwaitress, which we just got rid
of.

Anyway (even though I just threw your code out of the window :( ) thanks
for the pull request.

**Pull request closed without merging**
