### PR TITLE
Increased delay, retries, etc

### PR DESCRIPTION
**Pull request by gdudek**
There are a few different changes combined here, not all of which may be of general interest.
1) There are changes to allow stdin to be redirected from a file or /dev/null without disaster.
2) In such cases, status messages are written to a file in /tmp so thay can be more readily recovered by another client.  This is a bit ugly, but as opposed to using a pipe or a FIFO, it allows other processes that talk to pianobar to come and go.
3) There are a changes to player.c to increase robustness to very slow network connections.
4) There are a few cosmetic changes in the diagnostic messages, basically to assist me in debugging.

### CODE REVIEW

**Comment by PromyLOPh** [comment]
> 1) There are changes to allow stdin to be redirected from a file or /dev/null without disaster.
There’s a FIFO for remote control already. See manpage section “remote
control“. pianobar should also work fine with stdin redirected from
/dev/null, doesn’t it?

> 2) In such cases, status messages are written to a file in /tmp so thay can be more readily recovered by another client.  This is a bit ugly, but as opposed to using a pipe or a FIFO, it allows other processes that talk to pianobar to come and go.
See above and contrib/headless_pianobar.

> 3) There are a changes to player.c to increase robustness to very slow network connections.
We could add a timeout setting that affects both, player and API
requests, I suppose. Or would that be useless without having the retry
logic as well?

**Comment by gdudek** [comment]
I had some problems when I just redirected stdin from /dev/null and has seen other people commenting on difficulties. I wonder if that was due to the process handling a large volume of EOF's?   Without my patch I had trouble getting it to work smoothly with the control FIFO.  The file handling code, incidentally (and as you may know), is a bit funky and I presume it "evolved" as code often does.

I do use the normal remote control FIFO when PB is operated from the background, but I use the extra FIFO to allow the informational messages (like the station name) to be recovered by other processes on the system which might not be the once that started pianobar.  I could probably grab this from stdout, of course, but I made the (questionable) choice of having an extra FIFO to better control/limit the extent to which messages would get queued and be stale.  I am not sure if many other people would want this.

I do not think the retry logic is critical if the timeout is "right". I used both especially when tuning the timeout to allow the whole thing to be more robust.  It also depends a bit on the precise kind of network problems the process encounters.  In short, having the retry as well as a longer timeout is more robust but it's probably overkill for 99% of users.

Again, thanks for creating this nice program.

**Comment by PromyLOPh** [comment]
> I had some problems when I just redirected stdin from /dev/null and
> has seen other people commenting on difficulties. I wonder if that was
> due to the process handling a large volume of EOF's?   Without my
> patch I had trouble getting it to work smoothly with the control FIFO.
Hm, `./pianobar < /dev/null > /dev/null&` works fine here and I don’t
see what particular change in your pull request might have fixed the
issue. What exactly is “some problems”?

> The file handling code, incidentally (and as you may know), is a bit
> funky and I presume it "evolved" as code often does.
It dit.

> It also depends a bit on the precise kind of network problems the
> process encounters.  In short, having the retry as well as a longer
> timeout is more robust but it's probably overkill for 99% of users.
You’re right, timeout and retry tackle different issues (slow and
unstable connections). The former is just the lowest hanging fruit ;)

**Comment by gdudek** [comment]
Sorry, but I cannot recall exactly what the symptoms were.  I thing maybe the process was chewing a lot of CPU previously, presumably due to handling spurious EOF's.

**Comment by PromyLOPh** [comment]
I was pretty confident this was fixed with commit ce8503f8.

**Pull request closed without merging**
