### PR TITLE
Convert to CMake

### PR DESCRIPTION
**Pull request by DavidZemon**
I'm a big CMake fan. I feel it makes life easier as well as one-step closer to cross-platform.

Total lines in this pull request are 149... which is funny because that's _exactly_ the number of lines in your Makefile. But there's one big difference: 41 of those lines are in CPackConfig.cmake, which generates zip, tar.gz, rpm and debian packages for you. CMake supports OSX packages too, but I don't have a Mac to test with.

Along with the conversion to CMake, you'll be able to use [JetBrain's CLion](https://www.jetbrains.com/clion/) for free thanks to their OpenSource license policy (no, I'm not an employee - just a big fan).

### CODE REVIEW

**Comment by DavidZemon** [comment]
I have to add though - the debian and RPM package types need their "requires" lines added. Right now I simply have "TODO" in place.

**Comment by PromyLOPh** [comment]
It doesn’t work out-of-the-box:

```
…/pianobar/src/libpiano/crypt.c:50:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; i < outputLen; i++) {
  ^
…/pianobar/src/libpiano/crypt.c:50:2: note: use option -std=c99 or -std=gnu99 to compile your code
```

Also, CPackConfig.cmake is under version control, but apparently overwritten by
cmake(?). That’s not gonna work.

What are the advantages of cmake over plain gmake? (Besides being
cross-platform, which does not matter, because there is no platform pianobar
runs on, but gmake does not.)

**Comment by DavidZemon** [comment]
> It doesn’t work out-of-the-box:
> 
> ~~~~~~~~~
> …/pianobar/src/libpiano/crypt.c:50:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
>   for (size_t i = 0; i < outputLen; i++) {
>   ^
> …/pianobar/src/libpiano/crypt.c:50:2: note: use option -std=c99 or -std=gnu99 to compile your code
> ~~~~~~~~~

I'll fix that. I was hoping CMake was smart enough to do this automatically, but apparently not. I saw that snippet in your makefile and purposefully left it out. I'll also boot up my older version of Ubuntu to test on, that way I can hopefully catch some of the errors myself (I wrote this on Ubuntu 15.10 with GCC 5.2)

> Also, CPackConfig.cmake is under version control, but apparently overwritten by cmake(?). That’s not gonna work.

CMake builds should always be run out-of-source. You can run it in a child directory or sibling directory, but not the same. Personally, I run builds in a child directory called `bin`:
~~~~~~~~~
git clone....
cd pianobar
mkdir bin
cd bin
cmake ..
make
~~~~~~~~~
I find this to be a BIG advantage over gmake because you can clean up _all_ of your build files. With gmake, you're left to write your own `clean` target and hoping that it really does delete all generated files. When building out-of-source, you just delete the entire directory and start over, and you _know_ you're getting a fresh build, with nothing left over.

> What are the advantages of cmake over plain gmake?

Simplicity is a big one. As mentioned in the first comment, to only replicate the functionality in your Makefile requires ~110 lines instead of 149.
Integration with various IDEs, including Eclipse, Code::Blocks, CLion, XCode, and others. CLion reads the CMakeLists.txt file natively, and CMake is capable of generating metadata for all of the other IDEs (and more). Full list of generators: https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html (note that KDevelop4 and CLion support it natively, so they're not listed on that page)
And last, but not least, is the ability to quickly and easily generate debian and rpm packages (as well as OSX bundles I think but again, I can't test it)

**Comment by DavidZemon** [comment]
Okay, the compilation issue should be fixed.
I also found that I've been naming my CPack config file wrong in a lot of different projects. I checked with the CMake source code itself, and they name the file `CMakeCPack.cmake` instead of `CPackConfig.cmake`. So, I fixed that - no more overwriting the source code when you build in-source.

I went to test on my Ubuntu 14.04 machine, but it fails to compile (both with CMake and GMake). The [libavutil-dev package in trusty](http://packages.ubuntu.com/trusty/amd64/libavutil-dev/filelist) is missing `libavutils/frame.h`.

**Comment by PromyLOPh** [comment]
> I find this to be a BIG advantage over gmake because you can clean up all of
> your build files. 
Well, pianobar is quite small. thus getting `make clean` right is easy. It’s
more important that dependency tracking works correctly, i.e. files are
correctly rebuilt after a header changes.

> And last, but not least, is the ability to quickly and easily generate debian
> and rpm packages (as well as OSX bundles I think but again, I can't test it)
Packaging for all the different distributions and configurations is far too
difficult and time-consuming if you want to “get it right”. The generated
packages *might* work, but they certainly do not meet the distribution’s
standards and are not updated automatically.

Also it seems to be broken right now. The tgz is not generated and the debian
package gets version numbers wrong (no leading zero).

> Okay, the compilation issue should be fixed.
Yep, it is.

> I also found that I've been naming my CPack config file wrong in a lot of
> different projects. I checked with the CMake source code itself, and they
> name the file `CMakeCPack.cmake` instead of `CPackConfig.cmake`. So, I fixed
> that - no more overwriting the source code when you build in-source.
Works too.

> I went to test on my Ubuntu 14.04 machine, but it fails to compile (both with
> CMake and GMake). The libavutil-dev package in trusty is missing
> libavutils/frame.h.
That’s a known issue, libav 9.18 is too old and lacks a few functions pianobar
is using. So we’d need a version check here.

Before we put more work into this, let me say that right now, for *this*
project, I don’t see how cmake can provide any improvements, because the
Makefile works fine and is pretty easy to read and modify.

**Comment by DavidZemon** [comment]
> That’s a known issue, libav 9.18 is too old and lacks a few functions pianobar is using. So we’d need a version check here.

It's pretty easy to do that. Someone has [already done the work with CMake](https://bitbucket.org/sergiu/libav-cmake/src/51fb1cd97ce401e0fdebe8452d81accfcb8bc8e3/FindLibAV.cmake?at=default&fileviewer=file-view-default) to utilize CMake's `find_package` function, which determines the version of libav installed and then lets you make decisions based on that version (like whether or not to use something else).

> It’s more important that dependency tracking works correctly, i.e. files are correctly rebuilt after a header changes.

CMake does that much better than GMake. Header files are always scanned for changes - even ones not explicitly declared as source files.

**Comment by PromyLOPh** [comment]
> It's pretty easy to do that. Someone has [already done the work with
> CMake](https://bitbucket.org/sergiu/libav-cmake/src/51fb1cd97ce401e0fdebe8452d81accfcb8bc8e3/FindLibAV.cmake?at=default&fileviewer=file-view-default)
> to utilize CMake's `find_package` function, which determines the
> version of libav installed and then lets you make decisions based on
> that version (like whether or not to use something else).
Or use pkgconfig’s version.

> CMake does that much better than GMake. Header files are always
> scanned for changes - even ones not explicitly declared as source
> files.
Technically $PIANOBAR_HDR isn’t even required. That’s what the
compiler-generated *.d files are for. I assume cmake does the same.

**Comment by DavidZemon** [comment]
CMake doesn't appear to use the `*.d` files. It may actually have re-implemented that functionality internally.

**Pull request closed without merging**
