### PR TITLE
Add OS X notification example to eventcmd.sh.

### PR DESCRIPTION
**Pull request by mmb**

### CODE REVIEW

**Comment by cburmeister** [comment]
I have something similar here that's specific to OSX:

https://github.com/cburmeister/pianobar-notify

**Comment by PromyLOPh** [comment]
I think we should add that one-liner to eventcmd.sh instead.

**Comment by mmb** [comment]
@cburmeister Thanks I will check that out.

**Comment by mmb** [comment]
@PromyLOPh You mean as a commented out example?

**Comment by PromyLOPh** [comment]
> @PromyLOPh You mean as a commented out example?
Yes.

**Comment by mmb** [comment]
Changed to be an example in eventcmd.sh.

**Comment by PromyLOPh** [comment]
Merged, thanks!

**Pull request merged**
